const { Spell } = require('../models');

const spellData = [
    {
        name: "Acid Splash",
        school: "Conjuration",
        level: "Cantrip",
        damageType: "Acid",
        castingTime: '1 Action',
        duration: 'Instantaneous',
        range: '60ft.',
        components: 'V,S',
        attackSave: 'Dex Save',
    },
    {
        name: "Blade Ward",
        school: "Abjuration",
        level: "Cantrip",
        damageType: "Buff",
        castingTime: '1 Action',
        duration: '1 Round',
        range: 'Self',
        components: 'V,S',
        attackSave: 'None',
    },
    {
        name: "Booming Blade",
        school: "Evocation",
        level: "Cantrip",
        damageType: "Thunder",
        castingTime: '1 Action',
        duration: '1 Round',
        range: 'Self',
        components: 'S,M',
        attackSave: 'Melee',
    },
    {
        name: "Chill Touch",
        school: "Necromancy",
        level: "Cantrip",
        damageType: "Necrotic",
        castingTime: '1 Action',
        duration: '1 Round',
        range: '120 ft.',
        components: 'V,S',
        attackSave: 'Ranged',
    },
    {
        name: "Control Flames",
        school: "Transmutation",
        level: "Cantrip",
        damageType: "Control",
        castingTime: '1 Action',
        duration: 'Instantaneous',
        range: '60ft',
        components: 'S',
        attackSave: 'None',
    },
    {
        name: "Create Bonfire",
        school: "Conjuration",
        level: "Cantrip",
        damageType: "Fire",
        castingTime: '1 Action',
        duration: '1 Minute (Concentration)',
        range: '60ft. 5ft Cube.',
        components: 'V,S',
        attackSave: 'Dex Save',
    },
    {
        name: "Dancing Lights",
        school: "Evocation",
        level: "Cantrip",
        damageType: "Utility",
        castingTime: '1 Action',
        duration: '1 Minute (Concentration)',
        range: '120ft.',
        components: 'V,S,M',
        attackSave: 'None',
    },
    {
        name: "Druidcraft",
        school: "Transmutation",
        level: "Cantrip",
        damageType: "Control",
        castingTime: '1 Action',
        duration: 'Instantaneous',
        range: '30ft.',
        components: 'V,S',
        attackSave: 'None',
    },
    {
        name: "Eldritch Blast",
        school: "Evocation",
        level: "Cantrip",
        damageType: "Force",
        castingTime: '1 Action',
        duration: 'Instantaneous',
        range: '120ft.',
        components: 'V,S',
        attackSave: 'Ranged',
        details: 'A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage.',
    },
   {
        name: "Encode Thoughts",
        school: "Enchantment",
        level: "Cantrip",
        damageType: "Creation",
        castingTime: '1 Action',
        duration: '8 Hours',
        range: 'Self',
        components: 'S',
        attackSave: 'None',
    },
    {
        name: "Fire Bolt",
        school: "Evocation",
        level: "Cantrip",
        damageType: "Fire",
        castingTime: '1 Action',
        duration: 'Instantaneous',
        range: '120ft.',
        components: 'V,S',
        attackSave: 'Ranged',
    },
    {
        name: "Friends",
        school: "Enchantment",
        level: "Cantrip",
        damageType: "Buff",
        castingTime: '1 Action',
        duration: '1 Minute (Concentration)',
        range: 'Self',
        components: 'S,M',
        attackSave: 'None',
    },
    {
        name: "Frostbite",
        school: "Evocation",
        level: "Cantrip",
        damageType: "Cold",
        castingTime: '1 Action',
        duration: 'Instantaneous',
        range: '60ft.',
        components: 'V,S',
        attackSave: 'Con Save',
    },
];
const seedSpell = () => Spell.bulkCreate(spellData);

module.exports = seedSpell;